---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: POSTGRES_HOST
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: POSTGRES_DB