---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: development
  name: database-init
  labels:
    app: database
data:
  init.sql: |
    CREATE TABLE users (
      id SERIAL PRIMARY KEY,
      username VARCHAR(100) NOT NULL,
      email VARCHAR(100) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );