---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: development
  name: database-volume
  labels:
    type: local
    app: database
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql