---
apiVersion: v1
kind: Secret
metadata:
  namespace: development
  name: database-secret
  labels:
    app: database
type: Opaque
data:
  POSTGRES_USER: c2E=
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQhMTIz