---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: development
  name: frontend-config
  labels:
    app: frontend
data:
  BACKEND_API_URL: http://backend.development.svc.cluster.local:3000/api/users