---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BACKEND_API_URL